@startuml

skinparam usecase {
    BackgroundColor<< Public >>  LightBlue
    BackgroundColor<< Common >> LightGreen
}

actor Customer 
actor Merchant

(layout_main.jsp) << Common >>
(present.jsp) << Public >>
(info.jsp) << Public >>
(user_reg.jsp) << Public >>
(login.jsp) << Public >>
(category_list.jsp) << Public >>
(product_list.jsp) << Public >>
(product_view.jsp) << Public >>

Customer - (present.jsp)
(present.jsp) - Merchant

(present.jsp) -up-> (layout_main.jsp)
(user_reg.jsp) -down-> (layout_main.jsp)
(login.jsp) -up-> (user_reg.jsp) 
(login.jsp) -down-> (layout_main.jsp)
(user_view.jsp) .left-> (layout_main.jsp)

(info.jsp) .up-> (present.jsp)
(category_list.jsp) .up-> (present.jsp)
(category_create.jsp) .up-> (category_list.jsp)
(category_edit.jsp) .up-> (category_list.jsp)

(product_list.jsp) .up-> (category_list.jsp)
(product_create.jsp) .up-> (product_list.jsp)
(product_view.jsp) .up-> (product_list.jsp)
(product_edit.jsp) .up-> (product_view.jsp)

@enduml